version: '3.8'

services:
  ollama1:
    container_name: ollama1
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
    networks:
      - ollama-network1
  ollama-init:
    container_name: ollama-init
    depends_on:
      - ollama1
    image: 'ollama/ollama:latest'
    entrypoint: [ "ollama" ]
    command: ["pull", "llama3.2"]
    environment:
      - OLLAMA_PORT=11434
      - OLLAMA_HOST=ollama1
    networks:
      - ollama-network1

networks:
  ollama-network1:
    driver: bridge



